#%Module1.0
module-whatis "NEURON simulator"
module-whatis "Version: VERSION"
module-whatis "Description: abyss"
module-whatis "Compiler: ROLLCOMPILER"
module-whatis "MPI Flavors: ROLLMPI"
setenv NEURONHOME /opt/neuron/share/nrn
append-path PATH /opt/neuron/x86_64/bin
append-path PYTHONPATH /opt/neuron/lib/python2.7/site-packages
append-path LD_LIBRARY_PATH /opt/neuron/x86_64/lib
module load gnu gsl python
